/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t volatile *const pClkCtrlReg = (uint32_t*)0x40023830;
	uint32_t volatile *const pPortDModeReg  = (uint32_t*)0x40020C00;
	uint32_t volatile *const pPortDOutReg = (uint32_t*)0x40020C14;

	uint32_t volatile *const pPortAModeReg = (uint32_t*)0x40020000;
	uint32_t const volatile *const pPortAInputReg = (uint32_t*)0x40020010;
	//1. enable clock for GPIO peripheral A and D in the AHB1ENR (SET THE 3rd BIT POSITION for D, 0th BIT POSITION for A)
	*pClkCtrlReg |= (1<<3);
	*pClkCtrlReg |= (1<<0);

	//2. configure the mode of the IO pin as output
	//a. clear the 24th and 25th bit positions 	(CLEAR)
	*pPortDModeReg &= ~(3<<24);
	//b. make 24th bit position as 1 (SET)
	*pPortDModeReg |= (1<<24);
	// Configure PA0 as input mode (GPIOA MODE REGISTER)
	*pPortAModeReg &= ~(3<<0);
	while (1){
		// read the pin status of the pin PA0 (GPIOA INPUT DATA REG)
		uint8_t pinStatus = (uint8_t)(*pPortAInputReg & 0x1); // zero out all other bits except bit 0

		if (pinStatus){
			// turn on the LED
			*pPortDOutReg |= (1<<12);
		} else {
			// turn off the LED
			*pPortDOutReg &= ~(1<<12);
		}

	}
//	while (1){
//		//3. SET 12th bit of the output data register to make I/O pin-12 as HIGH
//		*pPortDOutReg |= (1<<12);
//
//		// a software delay added to mimic the led toggle behavior
//		for (uint32_t i=0; i < 300000; i++);
//
//		*pPortDOutReg &= ~(1<<12);
//
//		for (uint32_t i=0; i < 300000; i++);
//	}
}

